server:
  port: 8080

spring:
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:testdb;DB_CLOSE_DELAY=-1
    username: sa
    password: sa
#  jpa:
#    show-sql: true
#    properties:
#      hibernate:
#        format_sql: true

logging:
  pattern:
    console: "%d{HH:mm:ss.SSS} %magenta([%thread]) %highlight(%-5level) %logger{1}.%M - %msg%n"
  level:
    lv.dp: DEBUG
    org.springframework.web.filter.CommonsRequestLoggingFilter: DEBUG
