server:
  port: 8080

spring:
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:db;DB_CLOSE_DELAY=-1
    username: sa
    password: sa
  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true

logging:

  pattern:
    console: "%d{HH:mm:ss.SSS} %magenta([%thread]) %highlight(%-5level) %user %userIp %userCountry %logger{1}.%M - %msg%n"
    file: "%d{yyyy-MM-dd HH:mm:ss.SSS} %magenta([%thread]) %highlight(%-5level) %user %userIp %userCountry %logger{1}.%M - %msg%n"
  level:
    org.springframework.web.filter.CommonsRequestLoggingFilter: DEBUG
